[main]
font=monospace:weight=normal:size=12

[bell]
urgent=no
notify=no

[scrollback]
lines=10000

[cursor]
style=block
blink=yes

[mouse]
hide-when-typing=yes

[colors]
# Catppuccin Mocha
alpha=0.95

# Background and foreground
background=1e1e2e
foreground=cdd6f4

## Regular colors
regular0=45475a
regular1=f38ba8
regular2=a6e3a1
regular3=f9e2af
regular4=89b4fa
regular5=cba6f7
regular6=89dceb
regular7=bac2de

## Bright colors
bright0=585b70
bright1=f38ba8
bright2=a6e3a1
bright3=f9e2af
bright4=89b4fa
bright5=cba6f7
bright6=89dceb
bright7=a6adc8

## Selection colors
selection-foreground=cdd6f4
selection-background=414559

[csd]
preferred=server

[key-bindings]

[mouse-bindings]
